# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service
name: Deploy to Vercel
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

# See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read
  pull-requests: write

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Yarn
        run: |
          npm install
  
      # - name: Compile Check
      #   run: npx tsc

      - name: Deploy to Vercel develop
        id: dev_vercel_deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          mv "./public/css" "./dist/css"
          mv "./vercel.json" "./dist"
          npx vercel --token ${{ secrets.VERCEL_TOKEN }}

        env:
          VERCEL_TOKEN: "e6zAhQ5ufDMeXPZ62B9ZUF9H"
          VERCEL_PROJECT_ID: "prj_dMLdwDjaYOOmBnjAa6NRaSb9amUk"
          VERCEL_ORG_ID: "dBNZUFq1wfhvrdITtbTohoAl"

      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}


      - name: Deploy to Vercel prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          prodRun=""
          if [ "$BRANCH_NAME" = "main" ]; then
            prodRun="--prod"
          fi
          cd app
          mv "./public/css" "./dist/css"
          mv "./vercel.json" "./dist"
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} $prodRun
        env:
          VERCEL_TOKEN: "e6zAhQ5ufDMeXPZ62B9ZUF9H"
          VERCEL_PROJECT_ID: "prj_dMLdwDjaYOOmBnjAa6NRaSb9amUk"
          VERCEL_ORG_ID: "dBNZUFq1wfhvrdITtbTohoAl"

      - name: Set ENV Variables
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      # - name: Send Slack Notification
      #   if: github.event_name == 'push'
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   run: |
      #     if [ "$BRANCH_NAME" = "main" ]; then
      #       curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"A pull request has been merged on the MAIN branch of $REPO_NAME: https://optum-healthcare-frontend.vercel.app/ --- PASSWORD: Optum2024\"}" $SLACK_WEBHOOK_URL
      #     else
      #       curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"A pull request has been merged on the DEVELOP branch of $REPO_NAME: https://${{ steps.vercel_preview_url.outputs.preview_url }} --- PASSWORD: Optum2024\"}" $SLACK_WEBHOOK_URL  
      #     fi
